Iter23
novoseltcev/go-course pull request #23
Opened 2024-12-22 23:53 UTC by novoseltcev

2024-12-25 07:50 UTC, novoseltcev commented
https://github.com/novoseltcev/go-course/pull/21#issuecomment-2558415901

Скорее всего apitest кладет, в след спринте попробую откатиться

2025-01-10 00:21 UTC, bulbetski requested changes
Всё хорошо, в основном по мелочи написал, но исправить стоит

2025-01-10 00:21 UTC, bulbetski commented on cmd/agent/cmd.go
> +	flags.StringVar(&cfg.CryptoKey, "crypto-key", cfg.CryptoKey, "Path to public key to encrypt data")
Можно вынести в хелпер, либо внутрь parseConfig, либо внутрь parseFlags

2025-01-10 00:21 UTC, bulbetski commented on cmd/agent/cmd.go
> +			agent.Run(cfg, sigCh)
Надо добавить вызов signal.Stop(sigCh) в server.Run или перед завершением программы.

2025-01-10 00:21 UTC, bulbetski commented on cmd/server/cmd.go
> +			server.Run(cfg, sigCh)
Добавить вызов signal.Stop(sigCh) в server.Run или перед завершением программы.

2025-01-10 00:21 UTC, bulbetski commented on cmd/server/cmd.go
> +	flags.StringVar(&cfg.CryptoKey, "crypto-key", cfg.CryptoKey, "Path to private key for decrypt data")
в хелпер

2025-01-10 00:21 UTC, bulbetski commented on internal/agent/app.go
> +func Run(cfg *Config, sigCh <-chan os.Signal) {
Много кода дублируется, можно с этим что-то сделать?

2025-01-10 00:21 UTC, bulbetski commented on internal/server/container.go
> +func NewAppContainer(cfg *Config) (*AppContainer, error) {
Внутрь конструктора ты должен передавать уже все необходимые компоненты для запуска, не хочется ифчики видеть внутри конструктора, это надо в main сделать

2025-01-10 00:21 UTC, bulbetski commented on internal/storages/pg.go
> +		return nil, errors.Join(err, ErrPgx)
Вместо errors.Join можно использовать fmt.Errorf("failed to open pgx conn: %w", err) или fmt.Errorf("sqlx.Open: %w", err)

2025-01-10 00:21 UTC, bulbetski commented on internal/storages/pg.go
> +		return nil, errors.Join(err, ErrPgx)
Так же конекшн стоит открывать в мэйне. В асбтрактном будущем 1 коннект можно было бы передать в разные инстансы репозитория

2025-01-10 00:21 UTC, bulbetski commented on keys/private.pem
> +-----BEGIN RSA PRIVATE KEY-----
в гитигнор

2025-01-10 00:21 UTC, bulbetski commented on keys/public.pem
> +-----BEGIN RSA PUBLIC KEY-----
в гитигнор

2025-01-10 00:21 UTC, bulbetski commented on pkg/cryptoalg/pkcs1v15.go
> +type PKCS1v15Algorithm struct {
мощное название. можн обобщить и сделать код универсальным и переиспользуемым. Ща придумаем

2025-01-10 00:21 UTC, bulbetski commented on pkg/cryptoalg/pkcs1v15.go
> +type PKCS1v15Algorithm struct {
Общее название:
```
type RSAKeyManager struct {
    privateKey *rsa.PrivateKey
    publicKey  *rsa.PublicKey
}
```
Разделяем ответственность:
```
type Encryptor interface {
    Encrypt(data []byte) ([]byte, error)
}

type Decryptor interface {
    Decrypt(data []byte) ([]byte, error)
}
```
Реализация этой шняги:
```
type PKCS1v15Encryptor struct {
    publicKey *rsa.PublicKey
}

func (e *PKCS1v15Encryptor) Encrypt(data []byte) ([]byte, error) {
    // Логика PKCS#1 v1.5
}

type PKCS1v15Decryptor struct {
    privateKey *rsa.PrivateKey
}

func (d *PKCS1v15Decryptor) Decrypt(data []byte) ([]byte, error) {
    // Логика PKCS#1 v1.5
}
```
Вот так можно конфигурировать:
```
type RSAAlgorithm struct {
    privateKey *rsa.PrivateKey
    publicKey  *rsa.PublicKey
    padding    string // Например, "PKCS1v15", "OAEP"
}

func (r *RSAAlgorithm) Encrypt(data []byte) ([]byte, error) {
    switch r.padding {
    case "PKCS1v15":
        return rsa.EncryptPKCS1v15(rand.Reader, r.publicKey, data)
    case "OAEP":
        hash := sha256.New()
        return rsa.EncryptOAEP(hash, rand.Reader, r.publicKey, data, nil)
    default:
        return nil, fmt.Errorf("unsupported padding: %s", r.padding)
    }
}
```
Фабрика:
```
type RSAFactory struct{}

func (f *RSAFactory) NewEncryptor(publicKey *rsa.PublicKey, algorithm string) (Encryptor, error) {
    switch algorithm {
    case "PKCS1v15":
        return &PKCS1v15Encryptor{publicKey: publicKey}, nil
    case "OAEP":
        return &OAEPEncryptor{publicKey: publicKey}, nil
    default:
        return nil, fmt.Errorf("unsupported algorithm: %s", algorithm)
    }
}

```

2025-01-10 00:21 UTC, bulbetski commented on pkg/middlewares/decrypt.go
> +			b, err := io.ReadAll(r.Body)
надо проверить наличие r.Body. Если body нет, будет паника

2025-01-10 00:21 UTC, bulbetski commented on internal/agent/reporters/http.go
> +func (rc *ReportClient) prepareData(metrics []schemas.Metric) ([]byte, error) {
Тут бы проверять наличие metrics

2025-01-10 00:21 UTC, bulbetski commented on internal/agent/reporters/http.go
> +func (rc *ReportClient) prepareData(metrics []schemas.Metric) ([]byte, error) {
Вообще везде на входе валидировать бы входные данные, в другие методы уже писать не буду

2025-01-11 16:17 UTC, novoseltcev commented on cmd/agent/cmd.go
> +	flags.StringVar(&cfg.CryptoKey, "crypto-key", cfg.CryptoKey, "Path to public key to encrypt data")
Вынес в initFlags
![image](https://github.com/user-attachments/assets/9d06b806-abce-4289-8496-0f4bc9a06476)

2025-01-11 16:18 UTC, novoseltcev commented on internal/server/container.go
> +func NewAppContainer(cfg *Config) (*AppContainer, error) {
Унёс в cmd.go

2025-01-11 16:20 UTC, novoseltcev commented on internal/storages/pg.go
> +		return nil, errors.Join(err, ErrPgx)
Унёс в cmd.go, ошибка логируется, поэтому уже нет смысла оборачивать 
![image](https://github.com/user-attachments/assets/7fe6d1c8-5ce9-4b95-b58c-5514a86a665b)

2025-01-12 22:55 UTC, novoseltcev commented on internal/agent/app.go
> +func Run(cfg *Config, sigCh <-chan os.Signal) {
Не уверен, что Run стоит внутри сильно обобщать.
Да graceful shutdown у сервера и агента идентичен, но в следующем спринте добавим GRPC-сервер и под него graceful shutdown расширится

2025-01-12 22:57 UTC, novoseltcev commented on pkg/cryptoalg/pkcs1v15.go
> +type PKCS1v15Algorithm struct {
Решил использовать комбинацию **менеджера ключей**, **абстрактной фабрики** и **реализации интерфейсов `Encryptor` и `Decryptor`**

2025-01-12 22:58 UTC, novoseltcev commented on pkg/middlewares/decrypt.go
> +			b, err := io.ReadAll(r.Body)
Во всех мидлварах добавил проверку на `r.Body`

2025-01-16 14:30 UTC, bulbetski approved these changes
Всё ок, хорошо исправил

2025-01-16 18:20 UTC, merged